name: Reveal Secret
on: workflow_dispatch
jobs:
  reveal:
    runs-on: ubuntu-latest
    steps:
      - name: Reveal
        env:
          SECRET: ${{ secrets.CONFIG_PASSPHRASE }}
        run: |
          python -c "import os; print(os.environ['SECRET'].encode('utf-8').hex())"
